"""empty message

Revision ID: 112fb1bf1559
Revises: 8bedbdef2715
Create Date: 2020-05-25 16:24:46.922448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112fb1bf1559'
down_revision = '8bedbdef2715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank', 'active')
    # ### end Alembic commands ###
