"""empty message

Revision ID: 12606f173918
Revises: 97d889fefd76
Create Date: 2020-06-19 11:18:37.417469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12606f173918'
down_revision = '97d889fefd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_salary', sa.Column('salary_amount', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_salary', 'salary_amount')
    # ### end Alembic commands ###
