"""empty message

Revision ID: 33085d429b21
Revises: beed47368b9c
Create Date: 2020-06-08 01:11:53.047956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33085d429b21'
down_revision = 'beed47368b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth_user_detail', ['last_name', 'first_name', 'middle_name', 'suffix'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_user_detail', type_='unique')
    # ### end Alembic commands ###
