"""empty message

Revision ID: 36692f925e36
Revises: 165bf524b3a9
Create Date: 2020-05-28 06:06:25.753905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36692f925e36'
down_revision = '165bf524b3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('interest_rate', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'interest_rate')
    # ### end Alembic commands ###
