"""empty message

Revision ID: 4d95609e2e30
Revises: 810956318d00
Create Date: 2020-06-12 12:01:28.059659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d95609e2e30'
down_revision = '810956318d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_salary', sa.Column('sg', sa.Integer(), nullable=True))
    op.add_column('member_salary', sa.Column('step', sa.Integer(), nullable=True))
    op.add_column('member_salary', sa.Column('user_detail_id', sa.Integer(), nullable=True))
    op.drop_constraint('member_salary_user_id_fkey', 'member_salary', type_='foreignkey')
    op.create_foreign_key(None, 'member_salary', 'auth_user_detail', ['user_detail_id'], ['id'], ondelete='CASCADE')
    op.drop_column('member_salary', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_salary', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'member_salary', type_='foreignkey')
    op.create_foreign_key('member_salary_user_id_fkey', 'member_salary', 'auth_user_detail', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('member_salary', 'user_detail_id')
    op.drop_column('member_salary', 'step')
    op.drop_column('member_salary', 'sg')
    # ### end Alembic commands ###
