"""empty message

Revision ID: 52e77bf6a7c0
Revises: 5963994f30c6
Create Date: 2020-04-25 13:58:00.017257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52e77bf6a7c0'
down_revision = '5963994f30c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_column('auth_user', 'is_enabled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('auth_user', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
