"""empty message

Revision ID: 5963994f30c6
Revises: fb59db822816
Create Date: 2020-04-25 13:07:56.100296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5963994f30c6'
down_revision = 'fb59db822816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
    op.drop_column('auth_user', 'confirmed_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('auth_user', 'email_confirmed_at')
    # ### end Alembic commands ###
