"""empty message

Revision ID: 59a3d67d029a
Revises: 13ce421439f7
Create Date: 2020-05-03 20:20:42.279366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a3d67d029a'
down_revision = '13ce421439f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('min_term', sa.Integer(), nullable=False),
    sa.Column('max_term', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('auth_role', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_role', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_table('service')
    # ### end Alembic commands ###
