"""empty message

Revision ID: 810956318d00
Revises: 33085d429b21
Create Date: 2020-06-09 08:25:06.471968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810956318d00'
down_revision = '33085d429b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth_user_detail', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_user_detail', type_='unique')
    # ### end Alembic commands ###
