"""empty message

Revision ID: 8bedbdef2715
Revises: d3e1d1e61018
Create Date: 2020-05-25 16:15:51.922977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bedbdef2715'
down_revision = 'd3e1d1e61018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bank', ['short_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank', type_='unique')
    # ### end Alembic commands ###
