"""empty message

Revision ID: 928b4e58738d
Revises: b48ca6705e1d
Create Date: 2020-06-23 03:11:21.899530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928b4e58738d'
down_revision = 'b48ca6705e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_salary', 'salary_amount')
    op.drop_column('member_salary_history', 'salary_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_salary_history', sa.Column('salary_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('member_salary', sa.Column('salary_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
