"""empty message

Revision ID: 97d889fefd76
Revises: 4d95609e2e30
Create Date: 2020-06-12 18:44:00.018329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d889fefd76'
down_revision = '4d95609e2e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_salary', sa.Column('salary', sa.Numeric(precision=15, scale=2), nullable=True))
    op.drop_column('member_salary', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_salary', sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.drop_column('member_salary', 'salary')
    # ### end Alembic commands ###
