"""empty message

Revision ID: c0a20065468e
Revises: 112fb1bf1559
Create Date: 2020-05-25 17:25:42.315771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a20065468e'
down_revision = '112fb1bf1559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bank', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank', type_='unique')
    # ### end Alembic commands ###
