"""empty message

Revision ID: c87937e64e86
Revises: fb07334e3d05
Create Date: 2020-06-04 22:11:58.290444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87937e64e86'
down_revision = 'fb07334e3d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('date_filed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'date_filed')
    # ### end Alembic commands ###
