"""empty message

Revision ID: cd8e0afe4acf
Revises: 2d4e78dd392e
Create Date: 2020-09-17 00:58:32.968276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8e0afe4acf'
down_revision = '2d4e78dd392e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('date_modified', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('employee_number', sa.String(length=20), nullable=True),
    sa.Column('trans_date', sa.Date(), nullable=True),
    sa.Column('period', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('contributor', sa.String(length=1), nullable=False),
    sa.Column('trans_type', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['employee_number'], ['auth_user.employee_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contribution')
    # ### end Alembic commands ###
