"""empty message

Revision ID: fb59db822816
Revises: 1f766e0416a1
Create Date: 2020-04-20 23:28:17.926521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb59db822816'
down_revision = '1f766e0416a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'active')
    # ### end Alembic commands ###
